all:
  children:
    proxmox:
      hosts:
        pve-mini:
          ansible_host: pve-mini
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

        pve-station:
          ansible_host: pve-station
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
