all:
  children:
    proxmox:
      hosts:
        pve-mini:
          ansible_host: pve-mini
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

        pve-station:
          ansible_host: pve-station
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    linux_guests:
      hosts:
        lab-general-01:
          ansible_host: 192.168.1.120
          ansible_user: will
          ansible_ssh_common_args: >-
            -o ProxyJump=root@pve-mini
